### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by jnthas** [mathcoll/t6#14]
Hey, 

I tried to install following the wiki steps, but I got some unexpected errors during the process, I'll try to list them here in order to improve the installing instructions

1) I got an error when running `npm install`:

```
Error: Package exports for '/home/jonathas/projects/t6/node_modules/snyk-docker-plugin/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
    at resolveExports (internal/modules/cjs/loader.js:393:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/jonathas/projects/t6/node_modules/snyk-docker-plugin/lib/experimental.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! t6@2.0.1 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the t6@2.0.1 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I could solve the issue just updating the node, I was using version v13.0.1 and updated to `nvm install v14.0.0`. Even after that, I got another error: 

```
Failed to get vulns

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! t6@2.0.1 snyk-protect: `snyk protect`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the t6@2.0.1 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonathas/.npm/_logs/2020-09-25T01_02_33_793Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! t6@2.0.1 prepublish: `npm run snyk-protect`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the t6@2.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
``` 

It solved after I ran `npm run snyk-protect` though.

2) I should rename all files located in /data with my hostname, not only the listed in the wiki

3) File `t6BuildVersion.json` is missing in the project root, I made a generic one with content
```
{
    "t6BuildVersion": "eb65f80c1d3d76959ae1cd1eca3c33eb",
    "t6BuildDate": "21/09/2020 20:42:06"
}
``` 

4) Firebase certificate missing used in for notifications: `require("./data/certificates/t6-app-firebase-adminsdk-rw4am-8cd8dc25f3.json");` I've created an service account in firebase for my project. Done.

5) Another private key missing in settings: `fs.readFileSync("/path/to/data/certificates/dkim/privatekey.txt", "utf8")`
I've just comment that line for a while.

6) Now I'm stuck here, "Activating influxDb", I've already installed influxdb, but nothing happens after this message.

``` 
npm start

> t6@2.0.1 start /home/jonathas/projects/t6
> node ./bin/www

24/Sep/2020:23:26:45 -0300 [INFO] [ 'Activating influxdb: http://localhost:8086/t6' ]
```

**Comment by mathcoll** [comment]
Hello @jnthas,

Thank you for reporting your detailed logs.

Can you please make sure you have "INFO" in your logLevel setting:
in the data/settings-xxxxx.js file you should see : logLevel = "LOG|DEBUG|INFO|WARNING|ERROR";

Then, restart the node server and you might see more details.
logs should be set on the log folder, usually on "/var/log/node/t6-access|error.log" ;
You can display those logs using :
`tail -f /var/log/node/*.log`

In case not displays on log output, then, try to open the following url on your browser :
http://127.0.0.1:3000/

it should works.

**Comment by jnthas** [comment]
Hi @mathcoll,

I did the following changes to make it work,

- Changed the `logLevel` to INFO like you mentioned
- I set the path for both params `logAccessFile` and `logErrorFile` to the same folder of project
- Changed baseUrlCdn to "" in order to make the static resources available

Now I can access the system on 127.0.0.1:3000, but when I try to add a user I get this error:

```
Error writting event to influxDb: ServiceNotAvailableError: No host available
    at Pool.stream (/home/jonathas/projects/t6/node_modules/influx/lib/src/pool.js:230:29)
    at /home/jonathas/projects/t6/node_modules/influx/lib/src/pool.js:166:18
    at new Promise (<anonymous>)
    at Pool.discard (/home/jonathas/projects/t6/node_modules/influx/lib/src/pool.js:165:16)
    at InfluxDB.writePoints (/home/jonathas/projects/t6/node_modules/influx/lib/src/index.js:859:27)
    at Object.t6events.add (/home/jonathas/projects/t6/t6events.js:23:14)
    at /home/jonathas/projects/t6/routes/users.js:267:13
    at Layer.handle [as handle_request] (/home/jonathas/projects/t6/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jonathas/projects/t6/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/jonathas/projects/t6/node_modules/express/lib/router/route.js:112:3)
 
```

It's related to influxdb, but the database is working properly, I could check doing:

```
> select * from "events"
name: events
------------
time			what	where		who
1601591773414236468	start	t6App:dev	self

``` 

Do you have any idea what is the problem? I have another question, is it possible to disable sending emails when a user is created? 

Thanks!

**Comment by mathcoll** [comment]
Hi,

There is certainly something not correctly set on your influxdb.
can you please try a 
> SHOW MEASUREMENTS
then
> select count(*) from "data"
and 
> select count(*) from "requests"

I'm not an expert in influxdb;
BTW, as influx is only used to store timeseries, it should not block you to start using t6 on setting up your Objects, Flows, and so on.

About the next question - (this should be another ticket :-))
> I have another question, is it possible to disable sending emails when a user is created?
On purpose, I'd say : "no, not possible".
But, if you'd  really like it, you can edit file "routes/users.js" at line 293, and comment/remove the piece of code 
> t6mailer.sendMail(mailOptions).then(function(info){
> [ ... ...]
> });

Actually, if you do that change, the email won't be sent, but as a consequence it would be tricky to set your password then.
So, I hope this process is not confusing :
* once you have POSTed a new user,
* then you need to POST on "{{ENDPOINT}}/v{{API_VERSION}}/users/instruction" with the email as payload, so that a token is generated for that user
* then a GET on "{{ENDPOINT}}/v{{API_VERSION}}/users/{{my_user_id}}/token" ; to get that token.. And I hope this will work for you, because it require a Bearer token as header...
* then a POST on "{{ENDPOINT}}/v{{API_VERSION}}/users/token/{{my_token_password_reset}}" with the new password in payload

See Api doc for more details : 
https://api.internetcollaboratif.info/docs/
