### ISSUE TITLE
Docker / Docker-Compose support

### ISSUE THREAD

**Issue by arthurd2** [mathcoll/t6#21]
Hey guys,
Pretty nice the installation guide you did there.
I'd like to know if the project has an official Docker Repository.
And if you suggest an Docker-Compose template.

Best regards!

**Comment by mathcoll** [comment]
I'm sorry, I'm not confident (and not competent) with Docker at all. I'm not an expert and I cannot make sure I will be able to maintain myself such repo for Docker.
Just in case you achieve something usable, please share it :-)

**Comment by arthurd2** [comment]
Don't worry.
Since you have a nice README, it won't be too hard.
Leave it to me.
;-)
