### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by unmanagedtn** [mathcoll/t6#5]
When will the rules be enclosed in github release

**Comment by mathcoll** [comment]
Hi unmanagedtn,
The api for Rules resources is ready and into github yet as beta test. :-)
The only missing part is the UI to manage rules via the webBrowser or mobile application. And documentation is missing as well.

**Comment by mathcoll** [comment]
Hi, decisionRule which is the event-based manager has been imported into github on 807d037059ff5d4183e90618782ee6cda9538b4e

Rules can be added, edited and deleted via Api;
Rules can be (partially) added via PWA; some nested structured rules are not user friendly in the UI;
