### ISSUE TITLE
Question - Windows

### ISSUE THREAD

**Issue by MPopti0n** [mathcoll/t6#6]
I'm pretty new to all this, sorry if it's a dumb question : 

is there a way to get t6 up and running on Windows 10 ??

**Comment by mathcoll** [comment]
Hi @MPopti0n,

t6 has not been tested on Windows OS, but it should works.
Nodejs seems available on Windows. You can find details on the nodejs website:
https://nodejs.org/en/download/current/

Please get back and confirm if you succeed or not, it might be usefull.

**Comment by mathcoll** [comment]
Actually, I tested it recently. Installed successfully and run well.
I didn't experienced any particular pain to install it and start server locally.

* Not tested SSL certificate on Windows OS to have https ; it should be feasible I guess.
* Not tested Influxdb on Windows OS

Please let me know if you had any trouble on your end I will support you. Any error message ?
